DEFAULT_PROVIDER_VENDOR = "Custom"
DEFAULT_TARGET_SERVER_TYPE = "streamable_http"
DEFAULT_TARGET_GRANT_TYPE = "client_credentials"

TARGET_SERVER_TYPE_SSE = "sse"
TARGET_SERVER_TYPE_STREAMABLE_HTTP = "streamable_http"
TARGET_SERVER_TYPES = {
    TARGET_SERVER_TYPE_SSE,
    TARGET_SERVER_TYPE_STREAMABLE_HTTP,
}

TARGET_STATUS_CREATING = "creating"
TARGET_STATUS_UPDATING = "updating"
TARGET_STATUS_READY = "ready"
TARGET_STATUS_FAILED = "failed"
TARGET_STATUS_DELETING = "deleting"
