MCP_SERVER_TYPE_STREAMABLE_HTTP = "streamable_http"
MCP_SERVER_TYPE_SSE = "sse"

MCP_ALLOWED_SERVER_TYPES = {
    MCP_SERVER_TYPE_STREAMABLE_HTTP,
    MCP_SERVER_TYPE_SSE,
}

OAUTH_VENDOR_CUSTOM = "Custom"
OAUTH_GRANT_TYPE_CLIENT_CREDENTIALS = "client_credentials"

TARGET_STATUS_CREATING = "creating"
TARGET_STATUS_UPDATING = "updating"
TARGET_STATUS_READY = "ready"
TARGET_STATUS_FAILED = "failed"
TARGET_STATUS_DELETING = "deleting"

TARGET_TRANSITIONAL_STATUSES = {TARGET_STATUS_CREATING, TARGET_STATUS_UPDATING}
